# Generated by Django 3.0 on 2019-12-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
    ]
