# Generated by Django 3.0 on 2019-12-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tag',
            new_name='tags',
        ),
    ]
