# Generated by Django 3.0 on 2019-12-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='brief',
            field=models.TextField(blank=True),
        ),
    ]
