# Generated by Django 3.0 on 2019-12-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brief',
            field=models.TextField(null=True),
        ),
    ]
