# Generated by Django 3.0 on 2019-12-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191225_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='avatar',
            field=models.ImageField(default='article/default.jpg', upload_to='article/%Y/%m%d/'),
        ),
    ]
